[general]
import = [
  "~/.config/alacritty/themes/tokyo_night.toml"
#   "~/.config/alacritty/themes/themes/coolnight.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

opacity = 0.77
blur = true
# option_as_alt = "Both"

[font]
size = 18.0

[font.normal]
family = "CaskaydiaMono Nerd Font"
style = "Regular"

[font.bold]
family = "CaskaydiaMono Nerd Font"
style = "Bold"

[font.italic]
family = "CaskaydiaMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "CaskaydiaMono Nerd Font"
style = "Bold Italic"




[[keyboard.bindings]]
key = "J"
mods = "Alt"
chars = "\x1bj"  # Envoie Alt+j à Vim

[[keyboard.bindings]]
key = "K"
mods = "Alt"
chars = "\x1bk"  # Envoie Alt+k à Vim

[[keyboard.bindings]]
key = "J"
mods = "Alt|Shift"
chars = "\x1bJ"  # Alt+Shift+j

[[keyboard.bindings]]
key = "K"
mods = "Alt|Shift"
chars = "\x1bK"  # Alt+Shift+k

[[keyboard.bindings]]
key = "W"
mods = "Alt"
chars = "\x1bw"  # Alt+w pour fermer buffer

[[keyboard.bindings]]
chars = "\u001bJ"
key = "J"
mods = "Command|Shift"


[[keyboard.bindings]]
chars = "\u001b/"
key = "Slash"
mods = "Command"
